apiVersion: "v1"
kind: Pod
metadata:
  name: extract-ocp4-cis-node-master
spec:
  containers:
    - name: extract-ocp4-cis-node-master
      image: registry.access.redhat.com/ubi8/ubi
      command: ["sleep", "3000"]
      volumeMounts:
      - mountPath: "/ocp4-cis-node-master-scan-results"
        name: master-scan-vol
  volumes:
    - name: master-scan-vol
      persistentVolumeClaim:
        claimName: ocp4-cis-node-master
